# Site settings
title: Dr Bushra Sadia
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:5000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dr Bushra Sadia
user_description: Currently searching for the next challengena in the field of computer science. In my previous position as a software engineer, I was responsible for designing and implementing software solutions for clients, as well as collaborating with cross-functional teams to identify and resolve technical issues.
user_title: PhD Computational Sciences and Engineering
email: bushra(dot)saadia(at)gmail(dot)com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: bushrasadia
github_username:  bsadia
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules', 'vendor']
